In [1]:
%ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 58B3-92B1

 C:\Python\AI프로그래밍 디렉터리

2024-11-12  오전 11:22    <DIR>          .
2024-11-12  오전 11:22    <DIR>          ..
2024-11-12  오전 11:22    <DIR>          .ipynb_checkpoints
2024-11-12  오전 10:51               135 myscript.py
2024-11-12  오전 09:30    <DIR>          PythonDataScienceHandbook-master
2024-11-12  오전 11:20                72 Untitled.ipynb
2024-11-12  오전 11:22                72 Untitled1.ipynb
               3개 파일                 279 바이트
               4개 디렉터리  427,432,591,360 바이트 남음


In [2]:
%run myscript.py

1 의 제곱은  1
2 의 제곱은  4
3 의 제곱은  9


In [1]:
import numpy

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
x=4

In [5]:
x='abc'

In [6]:
result = 0
for i in range(100):
    result += i

In [7]:
L = list(range(10))

In [8]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
type(L[0])

int

In [10]:
r = range(10)

In [11]:
r

range(0, 10)

In [12]:
r?

Type:        range
String form: range(0, 10)
Length:      10
Docstring:  
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).

In [14]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
import numpy as np

In [19]:
n = np.array([1,2,3,4])

In [20]:
n

array([1, 2, 3, 4])

In [21]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [22]:
np.array([3.14, 4, 2, 3], dtype='float32')

array([3.14, 4.  , 2.  , 3.  ], dtype=float32)

In [23]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [24]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
np.arange(0,20,2)   ## 기억할 것!! 0부터 20까지 2씩 증가

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [29]:
np.linspace(0,1,5)   ## 0에서 1까지의 구간에 5개 간격

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
np.linspace(0,1,10)   ## 0에서 1까지의 구간에 10개 간격

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [33]:
np.random.normal(0,1,(3,3))

array([[-0.73238529,  0.52933737,  0.34826696],
       [-0.57067828,  0.36159877,  0.99267149],
       [ 1.65064449, -0.42967936,  0.10074468]])

In [34]:
np.random.randint(0,10,(3,3))

array([[7, 3, 2],
       [7, 8, 9],
       [1, 8, 8]], dtype=int32)

In [56]:
np.random.seed(0)   ## seed값을 주면 random이더라도 항상 같은 값이 나옴
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))

In [59]:
x1
x2
x3

array([[[1, 2, 4, 2, 0],
        [3, 2, 0, 7, 5],
        [9, 0, 2, 7, 2],
        [9, 2, 3, 3, 2]],

       [[3, 4, 1, 2, 9],
        [1, 4, 6, 8, 2],
        [3, 0, 0, 6, 0],
        [6, 3, 3, 8, 8]],

       [[8, 2, 3, 2, 0],
        [8, 8, 3, 8, 2],
        [8, 4, 3, 0, 4],
        [3, 6, 9, 8, 0]]], dtype=int32)

In [58]:
print("x3 ndim", x3.ndim)


x3 ndim 3


In [61]:
print("x3 shape", x3.shape)

x3 shape (3, 4, 5)


In [63]:
x1[-1]

np.int32(4)

In [64]:
x2

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]], dtype=int32)

In [65]:
x2[-2]

array([0, 1, 5, 9], dtype=int32)

In [66]:
x2[-2,-1]

np.int32(9)

In [67]:
x1[1:5:2]

array([3, 4], dtype=int32)

In [68]:
x1

array([4, 3, 4, 4, 8, 4], dtype=int32)

In [69]:
x

'abc'

In [70]:
x=np.arange(10)

In [71]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
x[3:9:2]

array([3, 5, 7])

In [73]:
x[::2]

array([0, 2, 4, 6, 8])

In [74]:
x2

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]], dtype=int32)

In [75]:
x2[:2,:3]

array([[3, 7, 5],
       [0, 1, 5]], dtype=int32)

In [76]:
x2[::-1,::-1]

array([[0, 5, 0, 3],
       [9, 5, 1, 0],
       [5, 5, 7, 3]], dtype=int32)

In [80]:
l = [1,2,3,4,5,6,7]
l2 = l[:2:-1]   ##  슬라이싱은 사본을 만든다. l2를 수정해도 l은 변하지 않음

In [81]:
l2

[7, 6, 5, 4]

In [83]:
l2[0]=77

In [84]:
l2

[77, 6, 5, 4]

In [85]:
l

[1, 2, 3, 4, 5, 6, 7]

In [89]:
x2_1 = x2[::-1,::-1]  ## 사본이 아니고 view를 제공

In [90]:
x2_1

array([[0, 5, 0, 3],
       [9, 5, 1, 0],
       [5, 5, 7, 3]], dtype=int32)

In [91]:
x2_1[0,0]=99   ## 변경하면 원본이 수정

In [92]:
x2_1

array([[99,  5,  0,  3],
       [ 9,  5,  1,  0],
       [ 5,  5,  7,  3]], dtype=int32)

In [93]:
x2

array([[ 3,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5, 99]], dtype=int32)

In [94]:
x2_1 = x2[::-1,::-1].copy()   ##.copy()를 붙여야 사본 생성 (numpy 배열 슬라이싱에서)

In [95]:
x2_1[1,1]=88

In [96]:
x2_1

array([[99,  5,  0,  3],
       [ 9, 88,  1,  0],
       [ 5,  5,  7,  3]], dtype=int32)

In [97]:
x2

array([[ 3,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5, 99]], dtype=int32)

In [98]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
grid = grid.reshape((3,3))

In [101]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
grid.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [106]:
grid [np.newaxis, :]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [107]:
x = np.array([1,2,3])

In [108]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [110]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])